server:
  port: 8003
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB

  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848

#阿里云 vod
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      accessKeyId:  # 访问身份验证中用到用户标识
      accessKeySecret: # 用户用于加密签名字符串和oss用来验证签名字符串的密钥




